#!/bin/sh

echo ===
echo AUTO UPDATE 'configurations.cfg'
echo [$(realpath "..\\configurations.cfg")]

function cancel() {
	echo 'configurations.cfg' was not updated.
}
#Add all folders begining by \"./config/SAMPLE_\" to \"$(realpath "..\\configurations.cfg")\".
function add_config() {
	if ! grep -q "[Common]" ../configurations.cfg
	then
		echo "[Common]" >> ../configurations.cfg
		echo '(LOCAL_STUDIO_PATH)/configurations.cfg' was created.
	fi
	
	echo >> ../configurations.cfg
	
	for configFolder in ./config/SAMPLE_*/
	do {
		configFolder=${configFolder#'./config/'}
		configFolder=${configFolder%/}
		configName=${configFolder/'SAMPLE_'/'SAMPLE_2022_'}
		if  grep -q "$configName\s=" ../configurations.cfg
		then
			echo Found "$configName"
		else
			echo Adding $configName ...
			echo $configName = \${LOCAL_STUDIO_PATH}\\SCANeR-Samples-Pack-2022\\config\\$configFolder >> ../configurations.cfg
		fi
	} done
	echo '(LOCAL_STUDIO_PATH)/configurations.cfg' is up to date.;
}

add_config