#!/bin/sh

echo AUTO UPDATE 'configurations.cfg'
echo This will add all folders begining by \"./config/SAMPLE_\" to \"$(realpath "..\\configurations.cfg")\".

function cancel() {
	echo 'configurations.cfg' was not updated.
}

function add_config() {
	for configFolder in ./config/SAMPLE_*/
	do {
		configFolder=${configFolder#'./config/'}
		configFolder=${configFolder%/}
		configName=${configFolder/'SAMPLE_'/'SAMPLE_2022_'}
		echo Adding $configName ...
		echo $configName = \${STUDIO_PATH}\\SCANeRstudio_2022\\config\\$configFolder >> ../configurations.cfg
	} done
	echo Successfully updated \"$(realpath "..\\configurations.cfg")\".;
}

add_config